[build]
  publish = "dist"
  command = "npm run generate"

[[redirects]]
  from = "/200"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/200.html"
  to = "/"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[plugins]]
  package = "@netlify/plugin-sitemap"
  [plugins.inputs]
    exclude = [
      './dist/404.html',
      './dist/200.html',
    ]

[[plugins]]
  package = "netlify-plugin-cache-nuxt"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"
