[build]
  publish = "dist"
  command = "npm run generate"

[[redirects]]
  from = "/js/script.js"
  to = "https://plausible.io/js/plausible.outbound-links.js"
  status = 200

[[redirects]]
  from = "/api/event"
  to = "https://plausible.io/api/event"
  status = 202

[[context.production.plugins]]
  package = "@netlify/plugin-sitemap"
  [context.production.plugins.inputs]
    exclude = [
      './dist/404.html',
      './dist/portfolio/sbb-gewinnspiel/index.html',
      './dist/ja/portfolio/sbb-gewinnspiel/index.html',
      './dist/de/portfolio/sbb-online-game/index.html',
    ]
