[build]
  publish = "dist"
  command = "npm run generate"

[[redirects]]
  from = "/js/script.js"
  to = "https://plausible.io/js/plausible.outbound-links.js"
  status = 200

[[redirects]]
  from = "/api/event"
  to = "https://plausible.io/api/event"
  status = 202

[[redirects]]
  from = "/200"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/200.html"
  to = "/"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"


[[plugins]]
  package = "netlify-plugin-cache-nuxt"

[[context.production.plugins]]
  package = "@netlify/plugin-sitemap"
  [context.production.plugins.inputs]
    exclude = [
      './dist/404.html',
    ]

[[context.production.plugins]]
  package = "netlify-plugin-submit-sitemap"
