name: Run Eslint

on:
  push:
    branches:
      - main
    paths:
      - '**.js'
      - '**.vue'

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: bahmutov/npm-install@v1

      - run: npm run lint

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Chore: Lint JavaScript and Vue files"

